version: 1.0.{build}
skip_tags: true
configuration: Debug
before_build:
- ps: nuget restore
build:
  verbosity: minimal
test_script:
- ps: >-
    nuget install OpenCover
    
    nuget install coveralls.net
    
    $nunit              = Get-Command nunit3-console | Select -Expand Source -First 1
    
    $opencover          = Resolve-Path ".\OpenCover.*\tools\OpenCover.Console.exe" | Select -Expand Path
    
    $coveralls          = Resolve-Path ".\coveralls.net.*\tools\csmacnz.coveralls.exe" | Select -Expand Path
    
    $assemblies         = Resolve-Path ".\EntityFramework.LazyLoadLoggingInterceptor*Tests\bin\$env:CONFIGURATION\EntityFramework.LazyLoadLoggingInterceptor*Tests.dll" | Select -Expand Path
    
    $filters            = "+[EntityFramework.LazyLoadLoggingInterceptor*]*"
    
    & $opencover "-register:user" "-target:$nunit" "-targetargs:$assemblies" "-filter:$filters" "-output:opencoverCoverage.xml"

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID